
// Generated by Cadence Genus(TM) Synthesis Solution 23.17-s085_1
// Generated on: May 14 2026 15:51:10 +07 (May 14 2026 08:51:10 UTC)

// Verification Directory fv/viterbi_top 

module viterbi_top(clk, rst_n, i_start, i_data, o_data, o_done);
  input clk, rst_n, i_start;
  input [15:0] i_data;
  output [7:0] o_data;
  output o_done;
  wire clk, rst_n, i_start;
  wire [15:0] i_data;
  wire [7:0] o_data;
  wire o_done;
  wire [4:0] u_acs_pm_01;
  wire [1:0] w_slt_node;
  wire [4:0] u_acs_pm_11;
  wire [1:0] w_prev_st_01;
  wire [4:0] u_acs_pm_10;
  wire [1:0] w_prev_st_11;
  wire [4:0] u_acs_pm_00;
  wire [1:0] w_prev_st_10;
  wire [1:0] w_prev_st_00;
  wire [1:0] u_memory_r1_t3;
  wire [1:0] u_memory_r0_t3;
  wire [1:0] u_memory_r3_t3;
  wire [1:0] u_memory_r2_t3;
  wire [2:0] u_memory_trace;
  wire [1:0] u_memory_r0_t5;
  wire [1:0] u_memory_r1_t2;
  wire [1:0] u_memory_r2_t6;
  wire [1:0] u_memory_r3_t5;
  wire [1:0] u_memory_r1_t6;
  wire [1:0] u_memory_r0_t1;
  wire [1:0] u_memory_r0_t2;
  wire [1:0] u_memory_r0_t4;
  wire [1:0] u_memory_r1_t1;
  wire [1:0] u_memory_r0_t6;
  wire [1:0] u_memory_r2_t1;
  wire [1:0] u_memory_r1_t4;
  wire [1:0] u_memory_r1_t5;
  wire [1:0] u_memory_r2_t2;
  wire [1:0] u_memory_r3_t4;
  wire [1:0] u_memory_r3_t2;
  wire [1:0] u_memory_r3_t6;
  wire [1:0] u_memory_r2_t4;
  wire [1:0] u_memory_r2_t5;
  wire [1:0] u_memory_r3_t1;
  wire [1:0] u_memory_r1_t0;
  wire [1:0] u_memory_r0_t0;
  wire [1:0] u_memory_r1_t7;
  wire [1:0] u_memory_r2_t0;
  wire [1:0] u_memory_r0_t7;
  wire [1:0] u_memory_r3_t7;
  wire [1:0] u_memory_r2_t7;
  wire [1:0] u_memory_r3_t0;
  wire [2:0] u_memory_count;
  wire [1:0] u_traceback_current_node;
  wire [15:0] u_extract_shift_reg;
  wire [7:0] u_traceback_temp_data;
  wire [3:0] u_traceback_count;
  wire [3:0] u_extract_count;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED51, UNCONNECTED52, UNCONNECTED53, UNCONNECTED54;
  wire UNCONNECTED55, UNCONNECTED56, UNCONNECTED57, UNCONNECTED58,
       UNCONNECTED59, UNCONNECTED60, UNCONNECTED61, UNCONNECTED62;
  wire UNCONNECTED63, UNCONNECTED64, UNCONNECTED65, UNCONNECTED66,
       UNCONNECTED67, UNCONNECTED68, UNCONNECTED69, UNCONNECTED70;
  wire UNCONNECTED71, UNCONNECTED72, UNCONNECTED73, UNCONNECTED74,
       UNCONNECTED75, UNCONNECTED76, UNCONNECTED77, UNCONNECTED78;
  wire UNCONNECTED79, UNCONNECTED80, UNCONNECTED81, UNCONNECTED82,
       UNCONNECTED83, UNCONNECTED84, UNCONNECTED85, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_45, n_46, n_47, n_48, n_49, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_67, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_121, n_122, n_123, n_124, n_125, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_184, n_185, n_186, n_187, n_188, n_192;
  wire n_193, n_194, n_195, n_196, n_197, n_198, n_201, n_202;
  wire n_203, n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  wire n_214, n_215, n_216, n_217, n_218, n_219, n_220, n_221;
  wire n_222, n_223, n_224, n_225, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_239, n_240;
  wire n_241, n_242, n_243, n_244, n_245, n_246, n_247, n_248;
  wire n_249, n_250, n_251, n_252, n_253, n_255, n_256, n_258;
  wire n_259, n_261, n_262, n_263, n_265, n_266, n_267, n_268;
  wire n_269, n_270, n_271, n_272, n_273, n_274, n_275, n_276;
  wire n_277, n_278, n_279, n_280, n_281, n_282, n_284, n_285;
  wire n_286, n_287, n_288, n_289, n_290, n_291, n_293, n_294;
  wire n_295, n_296, n_297, n_298, n_299, n_300, n_302, n_303;
  wire n_304, n_305, n_307, n_308, n_309, n_310, n_311, n_312;
  wire n_313, n_314, n_315, n_316, n_317, n_318, n_319, n_320;
  wire n_321, n_322, n_324, n_325, n_326, n_327, n_328, n_329;
  wire n_330, n_331, n_332, n_333, n_334, n_335, n_336, n_337;
  wire n_338, n_339, n_340, n_342, n_343, n_344, n_345, n_346;
  wire n_347, n_348, n_349, n_350, n_351, n_352, n_353, n_354;
  wire n_355, n_356, n_357, n_358, n_359, n_360, n_361, n_362;
  wire n_363, n_364, n_365, n_366, n_367, n_368, n_369, n_370;
  wire n_371, n_372, n_373, n_374, n_375, n_376, n_377, n_378;
  wire n_379, n_380, n_381, n_382, n_383, n_384, n_385, n_386;
  wire n_387, n_388, n_389, n_390, n_391, n_392, n_393, n_394;
  wire n_395, n_396, n_398, n_399, n_400, n_401, n_402, n_403;
  wire n_404, n_405, n_406, n_407, n_408, n_409, n_410, n_411;
  wire n_412, n_413, n_414, n_415, n_416, n_417, n_418, n_419;
  wire n_420, n_421, n_422, n_423, n_424, n_425, n_426, n_427;
  wire n_428, n_429, n_430, n_431, n_432, n_433, n_434, n_435;
  wire n_436, n_437, n_438, n_439, n_440, n_441, n_442, n_443;
  wire n_444, n_446, n_447, n_448, n_449, n_450, n_451, n_452;
  wire n_453, n_454, n_455, n_456, n_457, n_458, n_459, n_460;
  wire n_461, n_462, n_463, n_464, n_465, n_466, n_467, n_468;
  wire n_469, n_470, n_472, n_473, n_474, n_475, n_476, n_477;
  wire n_478, n_479, n_480, n_481, n_483, n_484, n_485, n_486;
  wire n_487, n_488, n_489, n_490, n_492, n_493, n_494, n_496;
  wire n_497, n_498, n_499, n_500, n_501, n_502, n_503, n_504;
  wire n_505, n_507, n_508, n_509, n_510, n_512, n_514, n_515;
  wire n_516, n_517, n_518, n_519, n_520, n_521, n_522, n_524;
  wire n_525, n_526, n_527, n_530, n_531, n_532, n_534, n_536;
  wire n_537, n_538, n_539, n_540, n_541, n_542, n_543, n_544;
  wire n_545, n_546, n_547, n_549, n_550, n_551, n_552, n_553;
  wire n_554, n_555, n_557, n_558, n_559, n_561, n_562, n_563;
  wire n_564, n_565, n_566, n_567, n_568, n_569, n_570, n_571;
  wire n_572, n_573, n_574, n_575, n_576, n_577, n_578, n_579;
  wire n_580, n_581, n_582, n_583, n_584, n_585, n_587, n_588;
  wire n_589, n_590, n_591, n_593, n_594, n_595, n_615, n_616;
  wire n_617, n_618, n_619, n_620, n_621, n_622, n_623, n_624;
  wire n_625, n_626, n_627, n_628, n_629, u_acs_o_valid_d1,
       u_memory_read_hold, u_memory_read_mode;
  wire u_traceback_tracing, w_memory_done, w_sof_1, w_sof_3, w_valid_1,
       w_valid_3;
  DFFRX1 \u_acs_pm_01_reg[1] (.RN (rst_n), .CK (clk), .D (n_594), .Q
       (u_acs_pm_01[1]), .QN (n_271));
  DFFRX1 \u_acs_slt_node_reg[1] (.RN (rst_n), .CK (clk), .D (n_591), .Q
       (w_slt_node[1]), .QN (UNCONNECTED));
  DFFRX1 \u_acs_pm_01_reg[3] (.RN (rst_n), .CK (clk), .D (n_595), .Q
       (u_acs_pm_01[3]), .QN (n_294));
  DFFRX1 \u_acs_pm_11_reg[3] (.RN (rst_n), .CK (clk), .D (n_589), .Q
       (u_acs_pm_11[3]), .QN (n_34));
  DFFRX1 \u_acs_pm_01_reg[2] (.RN (rst_n), .CK (clk), .D (n_590), .Q
       (u_acs_pm_01[2]), .QN (n_2));
  DFFRX1 \u_acs_pm_01_reg[0] (.RN (rst_n), .CK (clk), .D (n_585), .Q
       (u_acs_pm_01[0]), .QN (n_259));
  DFFRX1 \u_acs_pm_01_reg[4] (.RN (rst_n), .CK (clk), .D (n_588), .Q
       (u_acs_pm_01[4]), .QN (n_275));
  OAI221X1 g11999__2398(.A0 (n_485), .A1 (n_593), .B0 (n_147), .B1
       (n_294), .C0 (n_581), .Y (n_595));
  OAI221X1 g12000__5107(.A0 (n_616), .A1 (n_593), .B0 (n_147), .B1
       (n_271), .C0 (n_582), .Y (n_594));
  DFFRX1 \u_acs_pm_11_reg[4] (.RN (rst_n), .CK (clk), .D (n_584), .Q
       (u_acs_pm_11[4]), .QN (n_277));
  OAI21X1 g12046__6260(.A0 (u_acs_o_valid_d1), .A1 (n_573), .B0 (n_39),
       .Y (n_591));
  DFFRX1 \u_acs_pm_11_reg[1] (.RN (rst_n), .CK (clk), .D (n_577), .Q
       (u_acs_pm_11[1]), .QN (n_272));
  DFFRX1 \u_acs_pm_11_reg[0] (.RN (rst_n), .CK (clk), .D (n_576), .Q
       (u_acs_pm_11[0]), .QN (n_223));
  DFFRX1 \u_acs_pm_11_reg[2] (.RN (rst_n), .CK (clk), .D (n_579), .Q
       (u_acs_pm_11[2]), .QN (n_263));
  OAI222X1 g12006__4319(.A0 (n_476), .A1 (n_587), .B0 (n_466), .B1
       (n_593), .C0 (n_147), .C1 (n_2), .Y (n_590));
  OAI21X1 g11998__8428(.A0 (n_484), .A1 (n_583), .B0 (n_572), .Y
       (n_589));
  OAI222X1 g12007__5526(.A0 (n_531), .A1 (n_587), .B0 (n_545), .B1
       (n_593), .C0 (n_147), .C1 (n_275), .Y (n_588));
  OAI222X1 g12003__6783(.A0 (n_575), .A1 (n_587), .B0 (n_574), .B1
       (n_593), .C0 (n_147), .C1 (n_259), .Y (n_585));
  OAI222X1 g12005__3680(.A0 (n_525), .A1 (n_583), .B0 (n_537), .B1
       (n_578), .C0 (n_147), .C1 (n_277), .Y (n_584));
  NAND2X1 g12021__1617(.A (n_470), .B (n_580), .Y (n_582));
  NAND2X1 g12020__2802(.A (n_486), .B (n_580), .Y (n_581));
  OAI222X1 g12001__1705(.A0 (n_451), .A1 (n_583), .B0 (n_502), .B1
       (n_578), .C0 (n_147), .C1 (n_263), .Y (n_579));
  OAI222X1 g12002__5122(.A0 (n_318), .A1 (n_583), .B0 (n_362), .B1
       (n_578), .C0 (n_147), .C1 (n_272), .Y (n_577));
  OAI222X1 g12004__8246(.A0 (n_575), .A1 (n_583), .B0 (n_574), .B1
       (n_578), .C0 (n_147), .C1 (n_223), .Y (n_576));
  DFFRX1 \u_acs_slt_node_reg[0] (.RN (rst_n), .CK (clk), .D (n_570), .Q
       (w_slt_node[0]), .QN (UNCONNECTED0));
  DFFRX1 \u_acs_prev_st_01_reg[0] (.RN (rst_n), .CK (clk), .D (n_571),
       .Q (w_prev_st_01[0]), .QN (n_1));
  AOI21X1 g12068__7098(.A0 (n_514), .A1 (n_569), .B0 (n_568), .Y
       (n_573));
  AOI22X1 g12009__6131(.A0 (n_483), .A1 (n_567), .B0 (n_181), .B1
       (u_acs_pm_11[3]), .Y (n_572));
  DFFRX1 \u_acs_pm_10_reg[1] (.RN (rst_n), .CK (clk), .D (n_565), .Q
       (u_acs_pm_10[1]), .QN (n_7));
  DFFRX1 \u_acs_pm_10_reg[3] (.RN (rst_n), .CK (clk), .D (n_564), .Q
       (u_acs_pm_10[3]), .QN (n_3));
  DFFRX1 \u_acs_prev_st_11_reg[0] (.RN (rst_n), .CK (clk), .D (n_562),
       .Q (w_prev_st_11[0]), .QN (n_0));
  INVX2 g12027(.A (n_587), .Y (n_580));
  DFFRX1 \u_acs_pm_10_reg[0] (.RN (rst_n), .CK (clk), .D (n_555), .Q
       (u_acs_pm_10[0]), .QN (n_228));
  DFFRX1 \u_acs_pm_00_reg[3] (.RN (rst_n), .CK (clk), .D (n_561), .Q
       (u_acs_pm_00[3]), .QN (n_384));
  DFFRX1 \u_acs_pm_00_reg[4] (.RN (rst_n), .CK (clk), .D (n_552), .Q
       (u_acs_pm_00[4]), .QN (n_235));
  OAI22X1 g12018__1881(.A0 (n_181), .A1 (n_566), .B0 (n_147), .B1
       (n_1), .Y (n_571));
  MX2X1 g12065__5115(.A (n_569), .B (w_slt_node[0]), .S0
       (u_acs_o_valid_d1), .Y (n_570));
  DFFRX1 \u_acs_pm_10_reg[2] (.RN (rst_n), .CK (clk), .D (n_558), .Q
       (u_acs_pm_10[2]), .QN (n_279));
  DFFRX1 \u_acs_pm_00_reg[1] (.RN (rst_n), .CK (clk), .D (n_559), .Q
       (u_acs_pm_00[1]), .QN (n_22));
  DFFRX1 \u_acs_pm_10_reg[4] (.RN (rst_n), .CK (clk), .D (n_553), .Q
       (u_acs_pm_10[4]), .QN (n_11));
  NOR2X1 g12070__7482(.A (n_357), .B (n_569), .Y (n_568));
  CLKINVX1 g12026(.A (n_567), .Y (n_578));
  OR2X1 g12031__4733(.A (n_181), .B (n_566), .Y (n_593));
  OAI21X1 g12039__6161(.A0 (n_404), .A1 (n_563), .B0 (n_547), .Y
       (n_565));
  OAI21X1 g12038__9315(.A0 (n_478), .A1 (n_563), .B0 (n_549), .Y
       (n_564));
  OAI22X1 g12019__9945(.A0 (n_181), .A1 (n_557), .B0 (n_147), .B1
       (n_0), .Y (n_562));
  NAND2X1 g12034__2883(.A (n_147), .B (n_566), .Y (n_587));
  OAI221X1 g12028__2346(.A0 (n_449), .A1 (n_551), .B0 (n_147), .B1
       (n_384), .C0 (n_538), .Y (n_561));
  CLKINVX1 g12025(.A (n_550), .Y (n_559));
  OAI222X1 g12037__1666(.A0 (n_403), .A1 (n_563), .B0 (n_296), .B1
       (n_554), .C0 (n_147), .C1 (n_279), .Y (n_558));
  NOR2X1 g12032__7410(.A (n_181), .B (n_557), .Y (n_567));
  NAND2X1 g12033__6417(.A (n_147), .B (n_557), .Y (n_583));
  OAI222X1 g12041__5477(.A0 (n_543), .A1 (n_563), .B0 (n_627), .B1
       (n_554), .C0 (n_147), .C1 (n_228), .Y (n_555));
  OAI222X1 g12043__2398(.A0 (n_459), .A1 (n_563), .B0 (n_503), .B1
       (n_554), .C0 (n_147), .C1 (n_11), .Y (n_553));
  OAI221X1 g12040__5107(.A0 (n_507), .A1 (n_551), .B0 (n_147), .B1
       (n_235), .C0 (n_540), .Y (n_552));
  DFFRX1 \u_acs_pm_00_reg[0] (.RN (rst_n), .CK (clk), .D (n_544), .Q
       (u_acs_pm_00[0]), .QN (n_307));
  DFFRX1 \u_acs_pm_00_reg[2] (.RN (rst_n), .CK (clk), .D (n_542), .Q
       (u_acs_pm_00[2]), .QN (n_122));
  AOI222X1 g12029__6260(.A0 (n_297), .A1 (n_534), .B0 (n_181), .B1
       (u_acs_pm_00[1]), .C0 (n_624), .C1 (n_539), .Y (n_550));
  AOI22X1 g12081__4319(.A0 (n_278), .A1 (n_527), .B0 (n_13), .B1
       (n_522), .Y (n_569));
  DFFRX1 \u_acs_prev_st_10_reg[0] (.RN (rst_n), .CK (clk), .D (n_530),
       .Q (w_prev_st_10[0]), .QN (n_9));
  AOI22X1 g12049__8428(.A0 (n_479), .A1 (n_546), .B0 (n_181), .B1
       (u_acs_pm_10[3]), .Y (n_549));
  AOI22X1 g12048__5526(.A0 (n_405), .A1 (n_546), .B0 (n_181), .B1
       (u_acs_pm_10[1]), .Y (n_547));
  OAI21X1 g12052__6783(.A0 (n_545), .A1 (n_519), .B0 (n_532), .Y
       (n_566));
  DFFRX1 \u_acs_prev_st_00_reg[0] (.RN (rst_n), .CK (clk), .D (n_536),
       .Q (w_prev_st_00[0]), .QN (n_10));
  OAI222X1 g12036__3680(.A0 (n_543), .A1 (n_551), .B0 (n_626), .B1
       (n_541), .C0 (n_147), .C1 (n_307), .Y (n_544));
  OAI222X1 g12042__1617(.A0 (n_446), .A1 (n_551), .B0 (n_367), .B1
       (n_541), .C0 (n_147), .C1 (n_122), .Y (n_542));
  NAND2X1 g12044__2802(.A (n_499), .B (n_539), .Y (n_540));
  NAND2X1 g12045__1705(.A (n_448), .B (n_539), .Y (n_538));
  OAI21X1 g12051__5122(.A0 (n_537), .A1 (n_518), .B0 (n_526), .Y
       (n_557));
  OAI22X1 g12050__8246(.A0 (n_181), .A1 (n_534), .B0 (n_147), .B1
       (n_10), .Y (n_536));
  NAND2X1 g12056__7098(.A (n_531), .B (n_620), .Y (n_532));
  OAI22X1 g12058__6131(.A0 (n_181), .A1 (n_524), .B0 (n_147), .B1
       (n_9), .Y (n_530));
  CLKINVX1 g12059(.A (n_546), .Y (n_554));
  NAND4X1 g12095__1881(.A (u_acs_pm_00[4]), .B (u_acs_pm_10[4]), .C
       (n_521), .D (n_520), .Y (n_527));
  INVX2 g12053(.A (n_541), .Y (n_539));
  OAI21X1 g12057__5115(.A0 (n_517), .A1 (n_516), .B0 (n_525), .Y
       (n_526));
  NOR2X1 g12063__7482(.A (n_181), .B (n_524), .Y (n_546));
  NAND2X1 g12062__4733(.A (n_147), .B (n_524), .Y (n_563));
  NAND2X1 g12092__9315(.A (n_521), .B (n_520), .Y (n_522));
  NAND2X1 g12054__9945(.A (n_147), .B (n_551), .Y (n_541));
  NOR4X1 g12067__2883(.A (n_531), .B (n_494), .C (n_512), .D (n_505),
       .Y (n_519));
  OAI21X1 g12073__2346(.A0 (n_458), .A1 (n_504), .B0 (n_622), .Y
       (n_524));
  NOR3X1 g12061__1666(.A (n_493), .B (n_517), .C (n_515), .Y (n_518));
  CLKINVX1 g12060(.A (n_551), .Y (n_534));
  OR2X1 g12072__7410(.A (n_498), .B (n_515), .Y (n_516));
  OAI222X1 g12104__6417(.A0 (u_acs_pm_11[3]), .A1 (n_276), .B0 (n_510),
       .B1 (n_509), .C0 (u_acs_pm_01[3]), .C1 (n_514), .Y (n_520));
  CLKAND2X2 g12064__5477(.A (n_501), .B (n_508), .Y (n_551));
  NAND2X1 g12109__5107(.A (n_510), .B (n_509), .Y (n_521));
  OAI21X1 g12069__6260(.A0 (n_500), .A1 (n_488), .B0 (n_507), .Y
       (n_508));
  NOR2X1 g12077__4319(.A (n_489), .B (n_496), .Y (n_512));
  AND3X2 g12089__8428(.A (n_503), .B (n_481), .C (n_490), .Y (n_504));
  NOR3X1 g12079__5526(.A (n_502), .B (n_356), .C (n_497), .Y (n_515));
  OAI21X1 g12071__6783(.A0 (n_487), .A1 (n_500), .B0 (n_499), .Y
       (n_501));
  NAND2X1 g12075__3680(.A (n_537), .B (n_492), .Y (n_498));
  NOR2X1 g12076__1617(.A (n_452), .B (n_497), .Y (n_517));
  NOR2X1 g12080__2802(.A (n_477), .B (n_496), .Y (n_505));
  OAI21X1 g12116__1705(.A0 (n_468), .A1 (n_457), .B0 (n_480), .Y
       (n_509));
  CLKINVX1 g12083(.A (n_492), .Y (n_493));
  NAND3X1 g12119__5122(.A (n_352), .B (n_472), .C (n_467), .Y (n_489));
  OR2X1 g12084__8246(.A (n_499), .B (n_487), .Y (n_488));
  NOR2X1 g12085__7098(.A (n_486), .B (n_485), .Y (n_494));
  NAND2X1 g12086__6131(.A (n_484), .B (n_483), .Y (n_492));
  NOR2X1 g12087__1881(.A (n_484), .B (n_483), .Y (n_497));
  NAND2X1 g12125__5115(.A (n_344), .B (n_469), .Y (n_480));
  CLKAND2X2 g12090__7482(.A (n_486), .B (n_485), .Y (n_496));
  OAI21X1 g12102__4733(.A0 (n_479), .A1 (n_464), .B0 (n_475), .Y
       (n_490));
  OAI21X1 g12091__6161(.A0 (n_377), .A1 (n_474), .B0 (n_450), .Y
       (n_500));
  OAI21X1 g12114__9315(.A0 (n_478), .A1 (n_479), .B0 (n_460), .Y
       (n_481));
  NAND2X1 g12131__9945(.A (n_322), .B (n_476), .Y (n_477));
  DFFRX1 u_memory_read_hold_reg(.RN (rst_n), .CK (clk), .D (n_463), .Q
       (u_memory_read_hold), .QN (UNCONNECTED1));
  DFFRX1 u_memory_read_mode_reg(.RN (rst_n), .CK (clk), .D (n_462), .Q
       (u_memory_read_mode), .QN (n_158));
  INVX1 g12110(.A (n_465), .Y (n_475));
  DFFX1 \u_memory_r1_t3_reg[0] (.CK (clk), .D (n_440), .Q
       (u_memory_r1_t3[0]), .QN (UNCONNECTED2));
  DFFX1 \u_memory_r0_t3_reg[0] (.CK (clk), .D (n_441), .Q
       (u_memory_r0_t3[0]), .QN (UNCONNECTED3));
  NOR2X1 g12093__2883(.A (n_447), .B (n_474), .Y (n_487));
  OAI21X1 g12097__2346(.A0 (w_sof_1), .A1 (n_311), .B0 (n_473), .Y
       (n_483));
  NAND2X1 g12094__1666(.A (n_625), .B (n_473), .Y (n_486));
  OAI21X1 g12133__7410(.A0 (n_616), .A1 (n_361), .B0 (n_470), .Y
       (n_472));
  NAND3X1 g12132__6417(.A (n_468), .B (n_456), .C (n_455), .Y (n_469));
  NAND2X1 g12130__5477(.A (n_466), .B (n_454), .Y (n_467));
  DFFX1 \u_memory_r1_t3_reg[1] (.CK (clk), .D (n_439), .Q
       (u_memory_r1_t3[1]), .QN (UNCONNECTED4));
  DFFX1 \u_memory_r3_t3_reg[0] (.CK (clk), .D (n_444), .Q
       (u_memory_r3_t3[0]), .QN (UNCONNECTED5));
  DFFX1 \u_memory_r2_t3_reg[0] (.CK (clk), .D (n_443), .Q
       (u_memory_r2_t3[0]), .QN (UNCONNECTED6));
  DFFSX1 \u_memory_trace_reg[0] (.SN (rst_n), .CK (clk), .D (n_453), .Q
       (u_memory_trace[0]), .QN (n_16));
  AOI21X1 g12113__2398(.A0 (n_479), .A1 (n_464), .B0 (n_478), .Y
       (n_465));
  MX2X1 g12218__5107(.A (n_461), .B (u_memory_read_hold), .S0 (n_375),
       .Y (n_463));
  MX2X1 g12217__6260(.A (n_461), .B (u_memory_read_mode), .S0 (n_374),
       .Y (n_462));
  NOR2X1 g12124__4319(.A (n_406), .B (n_365), .Y (n_460));
  DFFX1 \u_memory_r0_t5_reg[0] (.CK (clk), .D (n_430), .Q
       (u_memory_r0_t5[0]), .QN (UNCONNECTED7));
  DFFX1 \u_memory_r1_t2_reg[0] (.CK (clk), .D (n_423), .Q
       (u_memory_r1_t2[0]), .QN (UNCONNECTED8));
  DFFX1 \u_memory_r2_t6_reg[0] (.CK (clk), .D (n_410), .Q
       (u_memory_r2_t6[0]), .QN (UNCONNECTED9));
  DFFX1 \u_memory_r3_t5_reg[0] (.CK (clk), .D (n_407), .Q
       (u_memory_r3_t5[0]), .QN (UNCONNECTED10));
  DFFX1 \u_memory_r1_t6_reg[1] (.CK (clk), .D (n_412), .Q
       (u_memory_r1_t6[1]), .QN (UNCONNECTED11));
  DFFX1 \u_memory_r1_t6_reg[0] (.CK (clk), .D (n_414), .Q
       (u_memory_r1_t6[0]), .QN (UNCONNECTED12));
  DFFX1 \u_memory_r0_t1_reg[0] (.CK (clk), .D (n_419), .Q
       (u_memory_r0_t1[0]), .QN (UNCONNECTED13));
  DFFX1 \u_memory_r0_t2_reg[0] (.CK (clk), .D (n_426), .Q
       (u_memory_r0_t2[0]), .QN (UNCONNECTED14));
  DFFX1 \u_memory_r0_t4_reg[0] (.CK (clk), .D (n_402), .Q
       (u_memory_r0_t4[0]), .QN (UNCONNECTED15));
  DFFX1 \u_memory_r1_t1_reg[0] (.CK (clk), .D (n_417), .Q
       (u_memory_r1_t1[0]), .QN (UNCONNECTED16));
  DFFX1 \u_memory_r0_t6_reg[0] (.CK (clk), .D (n_418), .Q
       (u_memory_r0_t6[0]), .QN (UNCONNECTED17));
  DFFX1 \u_memory_r2_t1_reg[0] (.CK (clk), .D (n_411), .Q
       (u_memory_r2_t1[0]), .QN (UNCONNECTED18));
  CLKINVX1 g12134(.A (n_458), .Y (n_459));
  CLKAND2X2 g12143__8428(.A (n_456), .B (n_455), .Y (n_457));
  DFFX1 \u_memory_r1_t4_reg[1] (.CK (clk), .D (n_422), .Q
       (u_memory_r1_t4[1]), .QN (UNCONNECTED19));
  DFFX1 \u_memory_r1_t5_reg[1] (.CK (clk), .D (n_434), .Q
       (u_memory_r1_t5[1]), .QN (UNCONNECTED20));
  DFFX1 \u_memory_r2_t2_reg[0] (.CK (clk), .D (n_421), .Q
       (u_memory_r2_t2[0]), .QN (UNCONNECTED21));
  DFFX1 \u_memory_r3_t4_reg[0] (.CK (clk), .D (n_437), .Q
       (u_memory_r3_t4[0]), .QN (UNCONNECTED22));
  DFFX1 \u_memory_r3_t2_reg[0] (.CK (clk), .D (n_424), .Q
       (u_memory_r3_t2[0]), .QN (UNCONNECTED23));
  DFFX1 \u_memory_r3_t6_reg[0] (.CK (clk), .D (n_408), .Q
       (u_memory_r3_t6[0]), .QN (UNCONNECTED24));
  DFFX1 \u_memory_r2_t4_reg[0] (.CK (clk), .D (n_428), .Q
       (u_memory_r2_t4[0]), .QN (UNCONNECTED25));
  DFFX1 \u_memory_r2_t5_reg[0] (.CK (clk), .D (n_435), .Q
       (u_memory_r2_t5[0]), .QN (UNCONNECTED26));
  DFFX1 \u_memory_r3_t1_reg[0] (.CK (clk), .D (n_409), .Q
       (u_memory_r3_t1[0]), .QN (UNCONNECTED27));
  DFFX1 \u_memory_r1_t5_reg[0] (.CK (clk), .D (n_431), .Q
       (u_memory_r1_t5[0]), .QN (UNCONNECTED28));
  DFFX1 \u_memory_r1_t1_reg[1] (.CK (clk), .D (n_415), .Q
       (u_memory_r1_t1[1]), .QN (UNCONNECTED29));
  DFFX1 \u_memory_r1_t2_reg[1] (.CK (clk), .D (n_436), .Q
       (u_memory_r1_t2[1]), .QN (UNCONNECTED30));
  CLKINVX1 g12139(.A (n_454), .Y (n_476));
  DFFX1 \u_memory_r1_t4_reg[0] (.CK (clk), .D (n_420), .Q
       (u_memory_r1_t4[0]), .QN (UNCONNECTED31));
  DFFSX1 \u_memory_trace_reg[2] (.SN (rst_n), .CK (clk), .D (n_429), .Q
       (u_memory_trace[2]), .QN (n_15));
  CLKINVX1 g12244(.A (n_432), .Y (n_453));
  OAI211X1 g12118__5526(.A0 (n_324), .A1 (n_451), .B0 (n_349), .C0
       (n_363), .Y (n_452));
  NAND2X1 g12099__6783(.A (n_449), .B (n_448), .Y (n_450));
  OAI222X1 g12115__3680(.A0 (n_446), .A1 (n_376), .B0 (n_364), .B1
       (n_360), .C0 (n_624), .C1 (n_359), .Y (n_447));
  MX2X1 g12279__1617(.A (w_prev_st_11[0]), .B (u_memory_r3_t3[0]), .S0
       (n_442), .Y (n_444));
  MX2X1 g12278__2802(.A (w_prev_st_10[0]), .B (u_memory_r2_t3[0]), .S0
       (n_442), .Y (n_443));
  MX2X1 g12275__1705(.A (w_prev_st_00[0]), .B (u_memory_r0_t3[0]), .S0
       (n_442), .Y (n_441));
  MX2X1 g12276__5122(.A (w_prev_st_01[0]), .B (u_memory_r1_t3[0]), .S0
       (n_442), .Y (n_440));
  MX2X1 g12277__8246(.A (w_prev_st_01[1]), .B (u_memory_r1_t3[1]), .S0
       (n_442), .Y (n_439));
  NOR2X1 g12100__7098(.A (n_449), .B (n_448), .Y (n_474));
  NAND2X1 g12101__6131(.A (w_sof_1), .B (n_448), .Y (n_473));
  AOI21X1 g12105__1881(.A0 (u_acs_pm_10[4]), .A1 (n_394), .B0 (n_395),
       .Y (n_525));
  DFFX1 \u_memory_r1_t0_reg[1] (.CK (clk), .D (n_386), .Q
       (u_memory_r1_t0[1]), .QN (UNCONNECTED32));
  OAI211X1 g12144__5115(.A0 (n_286), .A1 (n_289), .B0 (n_290), .C0
       (n_438), .Y (n_454));
  DFFX1 \u_memory_r0_t0_reg[0] (.CK (clk), .D (n_388), .Q
       (u_memory_r0_t0[0]), .QN (UNCONNECTED33));
  DFFX1 \u_memory_r1_t7_reg[1] (.CK (clk), .D (n_391), .Q
       (u_memory_r1_t7[1]), .QN (UNCONNECTED34));
  DFFX1 \u_memory_r2_t0_reg[0] (.CK (clk), .D (n_382), .Q
       (u_memory_r2_t0[0]), .QN (UNCONNECTED35));
  DFFX1 \u_memory_r0_t7_reg[0] (.CK (clk), .D (n_393), .Q
       (u_memory_r0_t7[0]), .QN (UNCONNECTED36));
  DFFX1 \u_memory_r1_t7_reg[0] (.CK (clk), .D (n_401), .Q
       (u_memory_r1_t7[0]), .QN (UNCONNECTED37));
  DFFX1 \u_memory_r3_t7_reg[0] (.CK (clk), .D (n_389), .Q
       (u_memory_r3_t7[0]), .QN (UNCONNECTED38));
  DFFX1 \u_memory_r2_t7_reg[0] (.CK (clk), .D (n_390), .Q
       (u_memory_r2_t7[0]), .QN (UNCONNECTED39));
  DFFX1 \u_memory_r1_t0_reg[0] (.CK (clk), .D (n_396), .Q
       (u_memory_r1_t0[0]), .QN (UNCONNECTED40));
  OAI211X1 g12142__7482(.A0 (n_304), .A1 (n_280), .B0 (n_281), .C0
       (n_438), .Y (n_470));
  DFFX1 \u_memory_r3_t0_reg[0] (.CK (clk), .D (n_381), .Q
       (u_memory_r3_t0[0]), .QN (UNCONNECTED41));
  AOI21X1 g12137__4733(.A0 (u_acs_pm_00[4]), .A1 (n_383), .B0 (n_373),
       .Y (n_458));
  DFFRX1 \u_memory_count_reg[1] (.RN (rst_n), .CK (clk), .D (n_392), .Q
       (u_memory_count[1]), .QN (UNCONNECTED42));
  DFFSX1 \u_memory_trace_reg[1] (.SN (rst_n), .CK (clk), .D (n_400), .Q
       (u_memory_trace[1]), .QN (n_195));
  MX2X1 g12256__6161(.A (u_memory_r3_t4[0]), .B (w_prev_st_11[0]), .S0
       (n_427), .Y (n_437));
  MX2X1 g12248__9315(.A (w_prev_st_01[1]), .B (u_memory_r1_t2[1]), .S0
       (n_425), .Y (n_436));
  MX2X1 g12249__9945(.A (w_prev_st_10[0]), .B (u_memory_r2_t5[0]), .S0
       (n_433), .Y (n_435));
  MX2X1 g12250__2883(.A (w_prev_st_01[1]), .B (u_memory_r1_t5[1]), .S0
       (n_433), .Y (n_434));
  AOI211X1 g12252__2346(.A0 (u_memory_trace[0]), .A1 (n_99), .B0
       (n_399), .C0 (n_378), .Y (n_432));
  MX2X1 g12254__1666(.A (w_prev_st_01[0]), .B (u_memory_r1_t5[0]), .S0
       (n_433), .Y (n_431));
  MX2X1 g12255__7410(.A (w_prev_st_00[0]), .B (u_memory_r0_t5[0]), .S0
       (n_433), .Y (n_430));
  CLKINVX1 g12314(.A (n_380), .Y (n_429));
  MX2X1 g12257__6417(.A (u_memory_r2_t4[0]), .B (w_prev_st_10[0]), .S0
       (n_427), .Y (n_428));
  MX2X1 g12259__5477(.A (w_prev_st_00[0]), .B (u_memory_r0_t2[0]), .S0
       (n_425), .Y (n_426));
  MX2X1 g12263__2398(.A (w_prev_st_11[0]), .B (u_memory_r3_t2[0]), .S0
       (n_425), .Y (n_424));
  MX2X1 g12260__5107(.A (w_prev_st_01[0]), .B (u_memory_r1_t2[0]), .S0
       (n_425), .Y (n_423));
  MX2X1 g12261__6260(.A (u_memory_r1_t4[1]), .B (w_prev_st_01[1]), .S0
       (n_427), .Y (n_422));
  MX2X1 g12262__4319(.A (w_prev_st_10[0]), .B (u_memory_r2_t2[0]), .S0
       (n_425), .Y (n_421));
  CLKXOR2X1 g12096__8428(.A (u_acs_pm_01[4]), .B (n_368), .Y (n_499));
  MX2X1 g12264__5526(.A (u_memory_r1_t4[0]), .B (w_prev_st_01[0]), .S0
       (n_427), .Y (n_420));
  MX2X1 g12286__6783(.A (u_memory_r0_t1[0]), .B (w_prev_st_00[0]), .S0
       (n_416), .Y (n_419));
  MX2X1 g12287__3680(.A (w_prev_st_00[0]), .B (u_memory_r0_t6[0]), .S0
       (n_413), .Y (n_418));
  MX2X1 g12290__1617(.A (u_memory_r1_t1[0]), .B (w_prev_st_01[0]), .S0
       (n_416), .Y (n_417));
  MX2X1 g12291__2802(.A (u_memory_r1_t1[1]), .B (w_prev_st_01[1]), .S0
       (n_416), .Y (n_415));
  MX2X1 g12292__1705(.A (w_prev_st_01[0]), .B (u_memory_r1_t6[0]), .S0
       (n_413), .Y (n_414));
  MX2X1 g12293__5122(.A (w_prev_st_01[1]), .B (u_memory_r1_t6[1]), .S0
       (n_413), .Y (n_412));
  MX2X1 g12295__8246(.A (u_memory_r2_t1[0]), .B (w_prev_st_10[0]), .S0
       (n_416), .Y (n_411));
  MX2X1 g12296__7098(.A (w_prev_st_10[0]), .B (u_memory_r2_t6[0]), .S0
       (n_413), .Y (n_410));
  MX2X1 g12298__6131(.A (u_memory_r3_t1[0]), .B (w_prev_st_11[0]), .S0
       (n_416), .Y (n_409));
  MX2X1 g12299__1881(.A (w_prev_st_11[0]), .B (u_memory_r3_t6[0]), .S0
       (n_413), .Y (n_408));
  MX2X1 g12300__5115(.A (w_prev_st_11[0]), .B (u_memory_r3_t5[0]), .S0
       (n_433), .Y (n_407));
  OAI22X1 g12135__7482(.A0 (n_405), .A1 (n_404), .B0 (n_403), .B1
       (n_369), .Y (n_406));
  MX2X1 g12265__4733(.A (u_memory_r0_t4[0]), .B (w_prev_st_00[0]), .S0
       (n_427), .Y (n_402));
  OAI21X1 g12161__6161(.A0 (n_371), .A1 (n_370), .B0 (n_273), .Y
       (n_455));
  INVX1 g12146(.A (n_385), .Y (n_478));
  MX2X1 g12281__9315(.A (w_prev_st_01[0]), .B (u_memory_r1_t7[0]), .S0
       (n_398), .Y (n_401));
  OAI211X1 g12253__9945(.A0 (n_195), .A1 (n_399), .B0 (n_398), .C0
       (n_379), .Y (n_400));
  MX2X1 g12288__2883(.A (u_memory_r1_t0[0]), .B (w_prev_st_01[0]), .S0
       (n_387), .Y (n_396));
  OAI21X1 g12108__2346(.A0 (u_acs_pm_10[4]), .A1 (n_394), .B0 (n_372),
       .Y (n_395));
  MX2X1 g12280__1666(.A (w_prev_st_00[0]), .B (u_memory_r0_t7[0]), .S0
       (n_398), .Y (n_393));
  CLKINVX1 g12243(.A (n_366), .Y (n_392));
  MX2X1 g12282__7410(.A (w_prev_st_01[1]), .B (u_memory_r1_t7[1]), .S0
       (n_398), .Y (n_391));
  MX2X1 g12283__6417(.A (w_prev_st_10[0]), .B (u_memory_r2_t7[0]), .S0
       (n_398), .Y (n_390));
  MX2X1 g12284__5477(.A (w_prev_st_11[0]), .B (u_memory_r3_t7[0]), .S0
       (n_398), .Y (n_389));
  MX2X1 g12285__2398(.A (u_memory_r0_t0[0]), .B (w_prev_st_00[0]), .S0
       (n_387), .Y (n_388));
  MX2X1 g12106__5107(.A (n_328), .B (n_484), .S0 (w_sof_1), .Y (n_485));
  MX2X1 g12289__6260(.A (u_memory_r1_t0[1]), .B (w_prev_st_01[1]), .S0
       (n_387), .Y (n_386));
  AOI211X1 g12151__4319(.A0 (n_384), .A1 (n_347), .B0 (w_sof_1), .C0
       (n_383), .Y (n_385));
  MX2X1 g12294__8428(.A (u_memory_r2_t0[0]), .B (w_prev_st_10[0]), .S0
       (n_387), .Y (n_382));
  MX2X1 g12297__5526(.A (u_memory_r3_t0[0]), .B (w_prev_st_11[0]), .S0
       (n_387), .Y (n_381));
  AOI21X1 g12317__6783(.A0 (u_memory_trace[2]), .A1 (n_379), .B0
       (n_378), .Y (n_380));
  NAND2X1 g12122__3680(.A (n_446), .B (n_376), .Y (n_377));
  NOR2X1 g12308__1617(.A (u_memory_read_mode), .B (n_378), .Y (n_375));
  AOI21X1 g12323__2802(.A0 (n_55), .A1 (n_109), .B0 (n_378), .Y
       (n_374));
  OAI21X1 g12148__1705(.A0 (u_acs_pm_00[4]), .A1 (n_383), .B0 (n_372),
       .Y (n_373));
  NAND2X1 g12167__5122(.A (n_371), .B (n_370), .Y (n_456));
  AND2X1 g12140__8246(.A (n_369), .B (n_403), .Y (n_464));
  AOI21X1 g12165__7098(.A0 (u_acs_pm_10[4]), .A1 (n_350), .B0 (n_351),
       .Y (n_531));
  NOR2X2 g12117__6131(.A (n_358), .B (n_368), .Y (n_448));
  CLKINVX1 g12127(.A (n_376), .Y (n_367));
  AOI21X1 g12251__1881(.A0 (u_memory_count[1]), .A1 (n_326), .B0
       (n_321), .Y (n_366));
  OAI211X1 g12136__5115(.A0 (u_acs_pm_00[4]), .A1 (n_336), .B0 (n_372),
       .C0 (n_319), .Y (n_507));
  AOI21X1 g12107__7482(.A0 (u_acs_pm_01[4]), .A1 (n_342), .B0 (n_343),
       .Y (n_503));
  DFFRX1 \u_traceback_current_node_reg[0] (.RN (rst_n), .CK (clk), .D
       (n_340), .Q (u_traceback_current_node[0]), .QN (n_4));
  AOI21X1 g12150__4733(.A0 (n_405), .A1 (n_404), .B0 (n_364), .Y
       (n_365));
  OAI21X1 g12149__6161(.A0 (n_362), .A1 (n_348), .B0 (n_361), .Y
       (n_363));
  CLKAND2X2 g12156__9315(.A (n_624), .B (n_359), .Y (n_360));
  NAND2X1 g12158__9945(.A (w_sof_1), .B (n_624), .Y (n_438));
  NAND2X1 g12334__2883(.A (n_353), .B (n_335), .Y (n_442));
  NOR2X1 g12121__2346(.A (n_355), .B (n_354), .Y (n_358));
  OAI211X1 g12231__1666(.A0 (u_acs_pm_10[0]), .A1 (n_357), .B0 (n_274),
       .C0 (n_308), .Y (n_370));
  CLKINVX1 g12128(.A (n_356), .Y (n_451));
  CLKAND2X2 g12126__7410(.A (n_355), .B (n_354), .Y (n_368));
  INVX2 g12326(.A (n_398), .Y (n_378));
  DFFRX1 \u_memory_count_reg[2] (.RN (rst_n), .CK (clk), .D (n_329), .Q
       (u_memory_count[2]), .QN (n_8));
  NAND2X1 g12333__6417(.A (n_331), .B (n_353), .Y (n_425));
  NOR2X1 g12332__5477(.A (n_333), .B (n_334), .Y (n_416));
  DFFRX1 \u_memory_count_reg[0] (.RN (rst_n), .CK (clk), .D (n_327), .Q
       (u_memory_count[0]), .QN (UNCONNECTED43));
  NAND2X1 g12175__2398(.A (n_616), .B (n_361), .Y (n_352));
  OAI21X1 g12174__5107(.A0 (u_acs_pm_10[4]), .A1 (n_350), .B0 (n_372),
       .Y (n_351));
  NAND2X1 g12162__6260(.A (n_362), .B (n_348), .Y (n_349));
  AOI21X1 g12152__4319(.A0 (n_313), .A1 (n_312), .B0 (n_354), .Y
       (n_376));
  INVX1 g12147(.A (n_337), .Y (n_449));
  OAI211X1 g12164__8428(.A0 (u_acs_pm_00[2]), .A1 (n_302), .B0 (n_372),
       .C0 (n_347), .Y (n_403));
  NAND2X1 g12335__5526(.A (n_346), .B (n_332), .Y (n_433));
  NAND2X1 g12336__6783(.A (n_353), .B (n_345), .Y (n_413));
  CLKAND2X2 g12352__3680(.A (n_346), .B (n_345), .Y (n_427));
  AOI22X1 g12258__1617(.A0 (u_acs_pm_10[2]), .A1 (n_339), .B0
       (u_acs_pm_00[2]), .B1 (n_357), .Y (n_344));
  OAI21X1 g12112__2802(.A0 (u_acs_pm_01[4]), .A1 (n_342), .B0 (n_372),
       .Y (n_343));
  OAI22X1 g12214__5122(.A0 (n_158), .A1 (n_288), .B0 (n_4), .B1 (n_91),
       .Y (n_340));
  OAI22X1 g12267__8246(.A0 (u_acs_pm_10[1]), .A1 (n_357), .B0
       (u_acs_pm_00[1]), .B1 (n_339), .Y (n_371));
  AOI22X1 g12268__7098(.A0 (u_acs_pm_10[3]), .A1 (n_339), .B0
       (u_acs_pm_00[3]), .B1 (n_357), .Y (n_510));
  XNOR2X1 g12120__6131(.A (n_338), .B (n_300), .Y (n_484));
  AOI211X1 g12153__5115(.A0 (n_384), .A1 (n_295), .B0 (w_sof_1), .C0
       (n_336), .Y (n_337));
  CLKINVX1 g12354(.A (n_334), .Y (n_335));
  AOI21X1 g12145__7482(.A0 (n_59), .A1 (n_303), .B0 (n_299), .Y
       (n_356));
  NAND2X1 g12123__4733(.A (u_acs_pm_10[3]), .B (n_299), .Y (n_394));
  AOI21X1 g12178__6161(.A0 (u_acs_pm_11[4]), .A1 (n_310), .B0 (n_309),
       .Y (n_537));
  NOR2X1 g12168__9315(.A (n_384), .B (n_347), .Y (n_383));
  NOR2X1 g12331__9945(.A (n_333), .B (n_330), .Y (n_387));
  NAND2X1 g12337__2883(.A (n_353), .B (n_332), .Y (n_398));
  CLKINVX1 g12353(.A (n_330), .Y (n_331));
  OAI22X1 g12347__2346(.A0 (n_325), .A1 (n_82), .B0 (n_8), .B1 (n_461),
       .Y (n_329));
  AOI22X1 g12213__1666(.A0 (n_34), .A1 (n_317), .B0 (u_acs_pm_11[3]),
       .B1 (n_316), .Y (n_328));
  OAI221X1 g12343__7410(.A0 (u_memory_read_mode), .A1 (n_270), .B0
       (u_memory_count[0]), .B1 (n_320), .C0 (n_43), .Y (n_327));
  OAI21X1 g12341__6417(.A0 (u_memory_count[0]), .A1 (n_325), .B0
       (n_461), .Y (n_326));
  CLKINVX1 g12211(.A (n_324), .Y (n_502));
  NAND2X1 g12229__5477(.A (n_256), .B (n_626), .Y (n_364));
  CLKINVX1 g12212(.A (n_322), .Y (n_466));
  NOR2X1 g12238__2398(.A (n_305), .B (n_575), .Y (n_361));
  NOR3X1 g12376__5107(.A (u_memory_count[1]), .B (n_320), .C (n_298),
       .Y (n_321));
  NAND2X1 g12157__6260(.A (u_acs_pm_00[4]), .B (n_336), .Y (n_319));
  CLKINVX1 g12358(.A (n_333), .Y (n_346));
  NOR2X1 g12363__4319(.A (n_315), .B (n_314), .Y (n_345));
  CLKINVX1 g12166(.A (n_318), .Y (n_348));
  AOI221X1 g12176__8428(.A0 (n_28), .A1 (n_317), .B0 (u_acs_pm_11[4]),
       .B1 (n_316), .C0 (n_52), .Y (n_545));
  NAND2X1 g12361__5526(.A (n_315), .B (n_314), .Y (n_334));
  NOR2X1 g12159__6783(.A (n_313), .B (n_312), .Y (n_354));
  AOI22X1 g12177__3680(.A0 (n_372), .A1 (n_284), .B0 (w_sof_1), .B1
       (n_208), .Y (n_404));
  CLKXOR2X1 g12216__1617(.A (u_acs_pm_11[3]), .B (n_310), .Y (n_311));
  OAI21X1 g12219__2802(.A0 (n_27), .A1 (n_310), .B0 (n_51), .Y (n_309));
  NAND2X1 g12307__1705(.A (n_307), .B (n_357), .Y (n_308));
  NAND2X1 g12266__5122(.A (u_acs_pm_10[3]), .B (n_291), .Y (n_350));
  OAI211X1 g12237__8246(.A0 (u_acs_pm_11[2]), .A1 (n_265), .B0 (n_372),
       .C0 (n_266), .Y (n_322));
  CLKINVX1 g12245(.A (n_305), .Y (n_574));
  OAI21X1 g12236__7098(.A0 (n_304), .A1 (n_285), .B0 (n_303), .Y
       (n_318));
  OAI211X1 g12235__6131(.A0 (u_acs_pm_11[2]), .A1 (n_267), .B0 (n_372),
       .C0 (n_268), .Y (n_324));
  NAND2X1 g12240__1881(.A (u_acs_pm_00[2]), .B (n_302), .Y (n_347));
  CLKINVX1 g12129(.A (n_300), .Y (n_299));
  NAND2X1 g12360__5115(.A (n_298), .B (n_315), .Y (n_330));
  CLKINVX1 g12173(.A (n_297), .Y (n_359));
  NOR2X1 g12364__7482(.A (n_298), .B (n_315), .Y (n_332));
  CLKINVX1 g12154(.A (n_296), .Y (n_369));
  NAND2X1 g12370__4733(.A (n_461), .B (n_293), .Y (n_333));
  OAI211X1 g12163__6161(.A0 (u_acs_pm_00[2]), .A1 (n_262), .B0 (n_372),
       .C0 (n_295), .Y (n_446));
  CLKXOR2X1 g12138__9315(.A (n_287), .B (n_294), .Y (n_479));
  NOR2X1 g12369__9945(.A (n_320), .B (n_293), .Y (n_353));
  NAND3X1 g12318__2883(.A (n_372), .B (u_acs_pm_10[2]), .C (n_289), .Y
       (n_290));
  OAI211X1 g12271__1666(.A0 (n_251), .A1 (n_250), .B0 (n_372), .C0
       (n_252), .Y (n_305));
  AOI21X1 g12270__7410(.A0 (u_acs_pm_11[1]), .A1 (n_229), .B0 (n_258),
       .Y (n_362));
  NAND2X1 g12273__5477(.A (n_57), .B (n_282), .Y (n_312));
  AOI22X1 g12321__2398(.A0 (n_141), .A1 (n_248), .B0 (w_memory_done),
       .B1 (n_246), .Y (n_288));
  OAI21X1 g12180__5107(.A0 (u_acs_pm_01[2]), .A1 (n_261), .B0 (n_287),
       .Y (n_296));
  OR2X1 g12141__6260(.A (n_294), .B (n_287), .Y (n_342));
  OAI22X1 g12179__4319(.A0 (w_sof_1), .A1 (n_255), .B0 (n_372), .B1
       (n_207), .Y (n_297));
  CLKINVX1 g12403(.A (n_298), .Y (n_314));
  NOR2X1 g12170__8428(.A (n_384), .B (n_295), .Y (n_336));
  NAND3X1 g12160__5526(.A (n_286), .B (n_304), .C (n_285), .Y (n_300));
  INVX2 g12340(.A (n_357), .Y (n_339));
  ADDHX1 g12247__6783(.A (u_acs_pm_00[1]), .B (n_227), .CO (n_302), .S
       (n_284));
  NAND3X1 g12346__3680(.A (n_372), .B (u_acs_pm_10[1]), .C (n_280), .Y
       (n_281));
  CLKINVX1 g12304(.A (n_317), .Y (n_316));
  NOR2X1 g12309__1617(.A (n_279), .B (n_289), .Y (n_291));
  NAND2X1 g12272__2802(.A (n_304), .B (n_285), .Y (n_303));
  CLKXOR2X1 g12302__1705(.A (n_249), .B (n_253), .Y (n_575));
  NAND2X1 g12351__5122(.A (n_236), .B (n_247), .Y (n_357));
  OAI22X1 g12378__8246(.A0 (n_277), .A1 (n_276), .B0 (n_275), .B1
       (n_514), .Y (n_278));
  AOI22X1 g12379__7098(.A0 (u_acs_pm_11[0]), .A1 (n_514), .B0
       (u_acs_pm_01[0]), .B1 (n_276), .Y (n_274));
  OAI22X1 g12374__6131(.A0 (n_272), .A1 (n_276), .B0 (n_271), .B1
       (n_514), .Y (n_273));
  AOI22X1 g12382__1881(.A0 (u_acs_pm_11[2]), .A1 (n_514), .B0
       (u_acs_pm_01[2]), .B1 (n_276), .Y (n_468));
  CLKINVX1 g12399(.A (n_270), .Y (n_325));
  NAND2X1 g12409__5115(.A (n_269), .B (u_memory_count[1]), .Y (n_293));
  NAND2X1 g12416__7482(.A (n_269), .B (u_memory_count[0]), .Y (n_298));
  NAND2X1 g12413__4733(.A (n_269), .B (u_memory_count[2]), .Y (n_315));
  NAND2X1 g12305__6161(.A (u_acs_pm_11[2]), .B (n_267), .Y (n_268));
  NAND2X1 g12306__9315(.A (u_acs_pm_11[2]), .B (n_265), .Y (n_266));
  NOR2X1 g12312__2883(.A (n_263), .B (n_265), .Y (n_317));
  NAND2X1 g12239__2346(.A (u_acs_pm_00[2]), .B (n_262), .Y (n_295));
  NAND2X1 g12241__1666(.A (u_acs_pm_01[2]), .B (n_261), .Y (n_287));
  OAI21X1 g12316__6417(.A0 (u_acs_pm_11[1]), .A1 (n_229), .B0 (n_372),
       .Y (n_258));
  CLKINVX1 g12338(.A (n_256), .Y (n_543));
  NAND2X1 g12410__5477(.A (w_sof_3), .B (w_valid_3), .Y (n_270));
  NAND2X1 g12324__2398(.A (n_231), .B (n_241), .Y (n_282));
  AOI21X1 g12325__5107(.A0 (n_271), .A1 (n_239), .B0 (n_261), .Y
       (n_405));
  OR2X1 g12311__6260(.A (n_263), .B (n_267), .Y (n_310));
  CLKXOR2X1 g12320__4319(.A (n_240), .B (u_acs_pm_00[1]), .Y (n_255));
  NAND2X1 g12344__8428(.A (n_251), .B (n_250), .Y (n_252));
  OAI21X1 g12322__5526(.A0 (n_249), .A1 (n_233), .B0 (n_217), .Y
       (n_285));
  NAND2X1 g12328__6783(.A (u_acs_pm_10[1]), .B (n_232), .Y (n_289));
  MX4X1 g12377__3680(.A (n_245), .B (n_244), .C (n_243), .D (n_242),
       .S0 (u_traceback_current_node[0]), .S1
       (u_traceback_current_node[1]), .Y (n_248));
  NAND2X1 g12375__1617(.A (u_acs_pm_10[4]), .B (n_224), .Y (n_247));
  MX4X1 g12380__2802(.A (n_245), .B (n_244), .C (n_243), .D (n_242),
       .S0 (w_slt_node[0]), .S1 (w_slt_node[1]), .Y (n_246));
  CLKXOR2X1 g12348__1705(.A (n_225), .B (n_53), .Y (n_256));
  OAI21X1 g12345__5122(.A0 (n_234), .A1 (n_230), .B0 (n_203), .Y
       (n_241));
  NOR2X1 g12327__8246(.A (n_22), .B (n_240), .Y (n_262));
  NOR2X1 g12330__7098(.A (n_271), .B (n_239), .Y (n_261));
  OR2X1 g12329__6131(.A (n_272), .B (n_229), .Y (n_267));
  OR2X1 g12349__1881(.A (n_272), .B (n_222), .Y (n_265));
  NAND2X1 g12406__5115(.A (n_235), .B (n_220), .Y (n_236));
  AOI21X1 g12350__7482(.A0 (n_234), .A1 (n_216), .B0 (n_233), .Y
       (n_253));
  CLKINVX1 g12356(.A (n_232), .Y (n_280));
  DFFRX1 u_acs_o_sof_reg(.RN (rst_n), .CK (clk), .D (n_221), .Q
       (w_sof_3), .QN (n_269));
  CLKINVX2 g12422(.A (n_276), .Y (n_514));
  NAND2X1 g12359__4733(.A (n_234), .B (n_230), .Y (n_231));
  OAI21X1 g12367__6161(.A0 (n_228), .A1 (n_214), .B0 (n_198), .Y
       (n_232));
  DFFRX1 u_acs_o_valid_reg(.RN (rst_n), .CK (clk), .D (n_147), .Q
       (w_valid_3), .QN (UNCONNECTED44));
  DFFRX1 \u_traceback_current_node_reg[1] (.RN (rst_n), .CK (clk), .D
       (n_202), .Q (u_traceback_current_node[1]), .QN (UNCONNECTED45));
  DFFRX1 \u_acs_prev_st_01_reg[1] (.RN (rst_n), .CK (clk), .D (n_211),
       .Q (w_prev_st_01[1]), .QN (UNCONNECTED46));
  OAI21X1 g12385__9315(.A0 (n_307), .A1 (n_251), .B0 (n_206), .Y
       (n_227));
  NAND3X1 g12404__9945(.A (u_acs_pm_00[4]), .B (n_219), .C (n_218), .Y
       (n_224));
  AOI22X1 g12381__2883(.A0 (u_acs_pm_11[0]), .A1 (n_196), .B0 (n_223),
       .B1 (n_234), .Y (n_250));
  NAND2X1 g12437__2346(.A (n_210), .B (n_201), .Y (n_276));
  NOR2X1 g12476__1666(.A (n_181), .B (n_372), .Y (n_221));
  NAND2X1 g12466__7410(.A (n_219), .B (n_218), .Y (n_220));
  INVX1 g12355(.A (n_209), .Y (n_239));
  INVX1 g12357(.A (n_205), .Y (n_240));
  NAND2X1 g12366__6417(.A (n_234), .B (n_216), .Y (n_217));
  AOI21X1 g12383__5477(.A0 (u_acs_pm_11[0]), .A1 (n_194), .B0 (n_215),
       .Y (n_229));
  NOR2X1 g12365__2398(.A (n_234), .B (n_216), .Y (n_233));
  AOI22X1 g12384__5107(.A0 (n_178), .A1 (n_234), .B0 (u_acs_pm_11[0]),
       .B1 (n_251), .Y (n_222));
  NOR2X1 g12415__6260(.A (n_215), .B (n_214), .Y (n_225));
  OR2X1 g12470__4319(.A (n_147), .B (w_prev_st_01[1]), .Y (n_211));
  NAND2X1 g12469__8428(.A (u_acs_pm_11[4]), .B (n_192), .Y (n_210));
  OAI21X1 g12362__5526(.A0 (n_259), .A1 (n_208), .B0 (n_207), .Y
       (n_209));
  OAI21X1 g12405__6783(.A0 (u_acs_pm_00[0]), .A1 (n_193), .B0 (n_234),
       .Y (n_206));
  OAI21X1 g12368__3680(.A0 (n_307), .A1 (n_208), .B0 (n_207), .Y
       (n_205));
  CLKINVX1 g12417(.A (n_197), .Y (n_202));
  CLKINVX2 g12401(.A (n_216), .Y (n_230));
  NAND2X1 g12511__1617(.A (n_275), .B (n_187), .Y (n_201));
  NAND2X1 g12479__2802(.A (n_18), .B (n_184), .Y (n_218));
  CLKINVX1 g12418(.A (n_215), .Y (n_198));
  AOI22X1 g12424__1705(.A0 (n_159), .A1 (n_176), .B0
       (u_traceback_current_node[1]), .B1 (n_142), .Y (n_197));
  CLKINVX1 g12421(.A (n_234), .Y (n_196));
  AOI22X1 g12412__5122(.A0 (w_sof_1), .A1 (n_251), .B0
       (u_acs_pm_10[0]), .B1 (n_372), .Y (n_249));
  OAI221X1 g12516__8246(.A0 (n_195), .A1 (n_157), .B0
       (u_memory_trace[1]), .B1 (n_62), .C0 (n_118), .Y (n_245));
  CLKINVX1 g12419(.A (n_194), .Y (n_214));
  OAI22X1 g12411__7098(.A0 (n_372), .A1 (n_251), .B0 (w_sof_1), .B1
       (n_259), .Y (n_203));
  OAI21X2 g12414__6131(.A0 (w_sof_1), .A1 (n_193), .B0 (n_180), .Y
       (n_216));
  NAND3X1 g12513__1881(.A (u_acs_pm_01[4]), .B (n_186), .C (n_185), .Y
       (n_192));
  DFFRX1 \u_extract_shift_reg_reg[13] (.RN (rst_n), .CK (clk), .D
       (n_164), .Q (u_extract_shift_reg[13]), .QN (UNCONNECTED47));
  DFFRX1 \u_extract_shift_reg_reg[7] (.RN (rst_n), .CK (clk), .D
       (n_169), .Q (u_extract_shift_reg[7]), .QN (UNCONNECTED48));
  DFFRX1 \u_extract_shift_reg_reg[11] (.RN (rst_n), .CK (clk), .D
       (n_165), .Q (u_extract_shift_reg[11]), .QN (UNCONNECTED49));
  DFFRX1 \u_extract_shift_reg_reg[14] (.RN (rst_n), .CK (clk), .D
       (n_163), .Q (u_extract_shift_reg[14]), .QN (UNCONNECTED50));
  DFFRX1 \u_extract_shift_reg_reg[15] (.RN (rst_n), .CK (clk), .D
       (n_162), .Q (u_extract_shift_reg[15]), .QN (UNCONNECTED51));
  DFFRX1 \u_traceback_temp_data_reg[7] (.RN (rst_n), .CK (clk), .D
       (n_175), .Q (u_traceback_temp_data[7]), .QN (UNCONNECTED52));
  DFFRX1 \u_extract_shift_reg_reg[12] (.RN (rst_n), .CK (clk), .D
       (n_161), .Q (u_extract_shift_reg[12]), .QN (UNCONNECTED53));
  DFFRX1 \u_extract_shift_reg_reg[2] (.RN (rst_n), .CK (clk), .D
       (n_166), .Q (u_extract_shift_reg[2]), .QN (UNCONNECTED54));
  DFFRX1 \u_extract_shift_reg_reg[9] (.RN (rst_n), .CK (clk), .D
       (n_167), .Q (u_extract_shift_reg[9]), .QN (UNCONNECTED55));
  DFFRX1 \u_extract_shift_reg_reg[4] (.RN (rst_n), .CK (clk), .D
       (n_171), .Q (u_extract_shift_reg[4]), .QN (UNCONNECTED56));
  DFFRX1 \u_extract_shift_reg_reg[10] (.RN (rst_n), .CK (clk), .D
       (n_172), .Q (u_extract_shift_reg[10]), .QN (UNCONNECTED57));
  DFFRX1 \u_extract_shift_reg_reg[5] (.RN (rst_n), .CK (clk), .D
       (n_170), .Q (u_extract_shift_reg[5]), .QN (UNCONNECTED58));
  DFFRX1 \u_extract_shift_reg_reg[8] (.RN (rst_n), .CK (clk), .D
       (n_168), .Q (u_extract_shift_reg[8]), .QN (UNCONNECTED59));
  DFFRX1 \u_extract_shift_reg_reg[6] (.RN (rst_n), .CK (clk), .D
       (n_160), .Q (u_extract_shift_reg[6]), .QN (UNCONNECTED60));
  DFFRX1 \u_extract_shift_reg_reg[3] (.RN (rst_n), .CK (clk), .D
       (n_177), .Q (u_extract_shift_reg[3]), .QN (UNCONNECTED61));
  NAND2X1 g12430__5115(.A (n_179), .B (n_251), .Y (n_194));
  NAND2X1 g12429__7482(.A (n_188), .B (n_251), .Y (n_207));
  CLKAND2X2 g12428__4733(.A (n_188), .B (n_193), .Y (n_215));
  NAND2X2 g12435__6161(.A (n_372), .B (n_188), .Y (n_234));
  NAND2X1 g12538__9315(.A (n_186), .B (n_185), .Y (n_187));
  OAI21X1 g12512__9945(.A0 (n_279), .A1 (n_123), .B0 (n_121), .Y
       (n_184));
  DFFRX1 u_traceback_o_done_reg(.RN (rst_n), .CK (clk), .D (n_154), .Q
       (o_done), .QN (UNCONNECTED62));
  DFFRX1 \u_traceback_count_reg[1] (.RN (rst_n), .CK (clk), .D (n_155),
       .Q (u_traceback_count[1]), .QN (n_5));
  NAND2X1 g12425__2883(.A (w_sof_1), .B (n_179), .Y (n_180));
  NAND2X1 g12423__2346(.A (n_223), .B (n_193), .Y (n_178));
  DFFRX1 \u_extract_shift_reg_reg[1] (.RN (rst_n), .CK (clk), .D
       (n_140), .Q (u_extract_shift_reg[1]), .QN (UNCONNECTED63));
  DFFRX1 \u_extract_shift_reg_reg[0] (.RN (rst_n), .CK (clk), .D
       (n_153), .Q (u_extract_shift_reg[0]), .QN (UNCONNECTED64));
  DFFRX1 \u_traceback_count_reg[2] (.RN (rst_n), .CK (clk), .D (n_152),
       .Q (u_traceback_count[2]), .QN (UNCONNECTED65));
  AND2X1 g12431__1666(.A (n_193), .B (n_179), .Y (n_208));
  DFFRX1 \u_traceback_count_reg[3] (.RN (rst_n), .CK (clk), .D (n_144),
       .Q (u_traceback_count[3]), .QN (UNCONNECTED66));
  CLKINVX1 g12439(.A (n_137), .Y (n_177));
  NAND4X1 g12514__7410(.A (n_119), .B (n_112), .C (n_117), .D (n_110),
       .Y (n_176));
  CLKINVX1 g12533(.A (n_143), .Y (n_175));
  NAND4X1 g12515__6417(.A (n_96), .B (n_103), .C (n_104), .D (n_101),
       .Y (n_244));
  NAND4X1 g12517__5477(.A (n_95), .B (n_98), .C (n_113), .D (n_94), .Y
       (n_243));
  NAND4X1 g12518__2398(.A (n_107), .B (n_115), .C (n_97), .D (n_100),
       .Y (n_242));
  CLKINVX1 g12501(.A (n_147), .Y (n_181));
  INVX2 g12467(.A (n_179), .Y (n_188));
  DFFRX1 \u_extract_count_reg[0] (.RN (rst_n), .CK (clk), .D (n_618),
       .Q (u_extract_count[0]), .QN (UNCONNECTED67));
  INVX2 g12468(.A (n_193), .Y (n_251));
  CLKINVX1 g12438(.A (n_138), .Y (n_172));
  CLKINVX1 g12440(.A (n_136), .Y (n_171));
  CLKINVX1 g12441(.A (n_146), .Y (n_170));
  CLKINVX1 g12442(.A (n_134), .Y (n_169));
  CLKINVX1 g12443(.A (n_133), .Y (n_168));
  CLKINVX1 g12444(.A (n_132), .Y (n_167));
  CLKINVX1 g12445(.A (n_131), .Y (n_166));
  CLKINVX1 g12446(.A (n_130), .Y (n_165));
  CLKINVX1 g12448(.A (n_139), .Y (n_164));
  CLKINVX1 g12449(.A (n_145), .Y (n_163));
  CLKINVX1 g12450(.A (n_150), .Y (n_162));
  CLKINVX1 g12447(.A (n_135), .Y (n_161));
  CLKINVX1 g12451(.A (n_156), .Y (n_160));
  DFFRX1 \u_extract_count_reg[1] (.RN (rst_n), .CK (clk), .D (n_617),
       .Q (u_extract_count[1]), .QN (UNCONNECTED68));
  NOR2X1 g12535__5107(.A (n_158), .B (n_84), .Y (n_159));
  AOI221X1 g12556__6260(.A0 (u_memory_r0_t7[0]), .A1 (n_60), .B0
       (u_memory_r0_t2[0]), .B1 (n_61), .C0 (n_75), .Y (n_157));
  AOI222X1 g12465__4319(.A0 (u_extract_shift_reg[4]), .A1 (n_149), .B0
       (i_start), .B1 (i_data[6]), .C0 (u_extract_shift_reg[6]), .C1
       (n_148), .Y (n_156));
  OAI21X1 g12543__8428(.A0 (u_traceback_count[1]), .A1 (n_151), .B0
       (n_70), .Y (n_155));
  NOR2X1 g12540__5526(.A (w_memory_done), .B (n_93), .Y (n_154));
  CLKINVX1 g12474(.A (n_128), .Y (n_153));
  OAI21X1 g12536__6783(.A0 (n_19), .A1 (n_151), .B0 (n_65), .Y (n_152));
  AOI222X1 g12464__3680(.A0 (u_extract_shift_reg[13]), .A1 (n_149), .B0
       (i_start), .B1 (i_data[15]), .C0 (u_extract_shift_reg[15]), .C1
       (n_148), .Y (n_150));
  DFFRX1 \u_traceback_temp_data_reg[0] (.RN (rst_n), .CK (clk), .D
       (n_88), .Q (u_traceback_temp_data[0]), .QN (UNCONNECTED69));
  NAND3X1 g12566__1617(.A (n_56), .B (n_25), .C (n_73), .Y (n_185));
  NAND2X1 g12545__2802(.A (n_195), .B (n_399), .Y (n_379));
  DFFRX1 \u_traceback_temp_data_reg[2] (.RN (rst_n), .CK (clk), .D
       (n_92), .Q (u_traceback_temp_data[2]), .QN (UNCONNECTED70));
  DFFRX1 \u_traceback_temp_data_reg[3] (.RN (rst_n), .CK (clk), .D
       (n_87), .Q (u_traceback_temp_data[3]), .QN (UNCONNECTED71));
  DFFRX1 \u_traceback_temp_data_reg[6] (.RN (rst_n), .CK (clk), .D
       (n_86), .Q (u_traceback_temp_data[6]), .QN (UNCONNECTED72));
  NAND2X1 g12472__1705(.A (w_valid_1), .B (u_extract_shift_reg[14]), .Y
       (n_179));
  NAND2X2 g12473__5122(.A (w_valid_1), .B (u_extract_shift_reg[15]), .Y
       (n_193));
  AOI222X1 g12455__8246(.A0 (u_extract_shift_reg[3]), .A1 (n_149), .B0
       (i_start), .B1 (i_data[5]), .C0 (u_extract_shift_reg[5]), .C1
       (n_148), .Y (n_146));
  AOI222X1 g12463__7098(.A0 (u_extract_shift_reg[12]), .A1 (n_149), .B0
       (i_start), .B1 (i_data[14]), .C0 (u_extract_shift_reg[14]), .C1
       (n_148), .Y (n_145));
  OAI22X1 g12537__6131(.A0 (n_12), .A1 (n_151), .B0 (w_memory_done),
       .B1 (n_20), .Y (n_144));
  AOI222X1 g12541__1881(.A0 (w_memory_done), .A1 (w_slt_node[1]), .B0
       (u_traceback_temp_data[7]), .B1 (n_142), .C0
       (u_traceback_current_node[1]), .C1 (n_141), .Y (n_143));
  CLKINVX1 g12475(.A (n_129), .Y (n_140));
  AOI222X1 g12462__5115(.A0 (u_extract_shift_reg[11]), .A1 (n_149), .B0
       (i_start), .B1 (i_data[13]), .C0 (u_extract_shift_reg[13]), .C1
       (n_148), .Y (n_139));
  AOI222X1 g12452__7482(.A0 (u_extract_shift_reg[8]), .A1 (n_149), .B0
       (i_start), .B1 (i_data[10]), .C0 (u_extract_shift_reg[10]), .C1
       (n_148), .Y (n_138));
  AOI222X1 g12453__4733(.A0 (u_extract_shift_reg[1]), .A1 (n_149), .B0
       (i_start), .B1 (i_data[3]), .C0 (u_extract_shift_reg[3]), .C1
       (n_148), .Y (n_137));
  AOI222X1 g12454__6161(.A0 (u_extract_shift_reg[2]), .A1 (n_149), .B0
       (i_start), .B1 (i_data[4]), .C0 (u_extract_shift_reg[4]), .C1
       (n_148), .Y (n_136));
  AOI222X1 g12461__9315(.A0 (u_extract_shift_reg[10]), .A1 (n_149), .B0
       (i_start), .B1 (i_data[12]), .C0 (u_extract_shift_reg[12]), .C1
       (n_148), .Y (n_135));
  AOI222X1 g12456__9945(.A0 (u_extract_shift_reg[5]), .A1 (n_149), .B0
       (i_start), .B1 (i_data[7]), .C0 (u_extract_shift_reg[7]), .C1
       (n_148), .Y (n_134));
  AOI222X1 g12457__2883(.A0 (u_extract_shift_reg[6]), .A1 (n_149), .B0
       (i_start), .B1 (i_data[8]), .C0 (u_extract_shift_reg[8]), .C1
       (n_148), .Y (n_133));
  AOI222X1 g12458__2346(.A0 (u_extract_shift_reg[7]), .A1 (n_149), .B0
       (i_start), .B1 (i_data[9]), .C0 (u_extract_shift_reg[9]), .C1
       (n_148), .Y (n_132));
  AOI222X1 g12459__1666(.A0 (u_extract_shift_reg[0]), .A1 (n_149), .B0
       (i_start), .B1 (i_data[2]), .C0 (u_extract_shift_reg[2]), .C1
       (n_148), .Y (n_131));
  AOI222X1 g12460__7410(.A0 (u_extract_shift_reg[9]), .A1 (n_149), .B0
       (i_start), .B1 (i_data[11]), .C0 (u_extract_shift_reg[11]), .C1
       (n_148), .Y (n_130));
  DFFRX1 \u_traceback_temp_data_reg[4] (.RN (rst_n), .CK (clk), .D
       (n_85), .Q (u_traceback_temp_data[4]), .QN (UNCONNECTED73));
  DFFRX1 \u_traceback_temp_data_reg[5] (.RN (rst_n), .CK (clk), .D
       (n_90), .Q (u_traceback_temp_data[5]), .QN (UNCONNECTED74));
  DFFRX1 \u_traceback_temp_data_reg[1] (.RN (rst_n), .CK (clk), .D
       (n_89), .Q (u_traceback_temp_data[1]), .QN (UNCONNECTED75));
  AOI22X1 g12481__6417(.A0 (u_extract_shift_reg[1]), .A1 (n_148), .B0
       (i_data[1]), .B1 (i_start), .Y (n_129));
  AOI22X1 g12480__5477(.A0 (u_extract_shift_reg[0]), .A1 (n_148), .B0
       (i_data[0]), .B1 (i_start), .Y (n_128));
  CLKBUFX2 g12503(.A (w_valid_1), .Y (n_147));
  DFFRX1 \u_traceback_o_data_reg[7] (.RN (rst_n), .CK (clk), .D (n_79),
       .Q (o_data[7]), .QN (UNCONNECTED76));
  DFFRX1 \u_traceback_o_data_reg[1] (.RN (rst_n), .CK (clk), .D (n_77),
       .Q (o_data[1]), .QN (UNCONNECTED77));
  DFFRX1 \u_traceback_count_reg[0] (.RN (rst_n), .CK (clk), .D (n_74),
       .Q (u_traceback_count[0]), .QN (n_6));
  NOR2X1 g12553__6260(.A (n_122), .B (n_629), .Y (n_123));
  NAND2X1 g12552__4319(.A (n_122), .B (n_629), .Y (n_121));
  DFFRX1 \u_traceback_o_data_reg[2] (.RN (rst_n), .CK (clk), .D (n_71),
       .Q (o_data[2]), .QN (UNCONNECTED78));
  DFFRX1 \u_traceback_o_data_reg[6] (.RN (rst_n), .CK (clk), .D (n_72),
       .Q (o_data[6]), .QN (UNCONNECTED79));
  DFFRX1 \u_traceback_o_data_reg[4] (.RN (rst_n), .CK (clk), .D (n_78),
       .Q (o_data[4]), .QN (UNCONNECTED80));
  DFFRX1 \u_traceback_o_data_reg[3] (.RN (rst_n), .CK (clk), .D (n_81),
       .Q (o_data[3]), .QN (UNCONNECTED81));
  DFFRX1 \u_traceback_o_data_reg[0] (.RN (rst_n), .CK (clk), .D (n_83),
       .Q (o_data[0]), .QN (UNCONNECTED82));
  DFFRX1 \u_traceback_o_data_reg[5] (.RN (rst_n), .CK (clk), .D (n_76),
       .Q (o_data[5]), .QN (UNCONNECTED83));
  AOI22X1 g12572__8428(.A0 (u_memory_r1_t3[1]), .A1 (n_106), .B0
       (u_memory_r1_t6[1]), .B1 (n_105), .Y (n_119));
  AOI22X1 g12549__5526(.A0 (u_memory_r0_t1[0]), .A1 (n_108), .B0
       (u_memory_r0_t4[0]), .B1 (n_116), .Y (n_118));
  AOI22X1 g12550__6783(.A0 (u_memory_r1_t4[1]), .A1 (n_116), .B0
       (u_memory_r1_t5[1]), .B1 (n_114), .Y (n_117));
  AOI22X1 g12551__3680(.A0 (u_memory_r3_t2[0]), .A1 (n_111), .B0
       (u_memory_r3_t5[0]), .B1 (n_114), .Y (n_115));
  AOI22X1 g12554__1617(.A0 (u_memory_r2_t4[0]), .A1 (n_116), .B0
       (u_memory_r2_t5[0]), .B1 (n_114), .Y (n_113));
  AOI22X1 g12555__2802(.A0 (u_memory_r1_t2[1]), .A1 (n_111), .B0
       (u_memory_r1_t7[1]), .B1 (n_102), .Y (n_112));
  AOI22X1 g12558__1705(.A0 (u_memory_r1_t0[1]), .A1 (n_109), .B0
       (u_memory_r1_t1[1]), .B1 (n_108), .Y (n_110));
  AOI22X1 g12560__5122(.A0 (u_memory_r3_t3[0]), .A1 (n_106), .B0
       (u_memory_r3_t6[0]), .B1 (n_105), .Y (n_107));
  AOI22X1 g12561__8246(.A0 (u_memory_r1_t4[0]), .A1 (n_116), .B0
       (u_memory_r1_t5[0]), .B1 (n_114), .Y (n_104));
  AOI22X1 g12562__7098(.A0 (u_memory_r1_t2[0]), .A1 (n_111), .B0
       (u_memory_r1_t7[0]), .B1 (n_102), .Y (n_103));
  AOI22X1 g12563__6131(.A0 (u_memory_r1_t0[0]), .A1 (n_109), .B0
       (u_memory_r1_t1[0]), .B1 (n_108), .Y (n_101));
  AOI22X1 g12564__1881(.A0 (u_memory_r3_t0[0]), .A1 (n_109), .B0
       (u_memory_r3_t1[0]), .B1 (n_108), .Y (n_100));
  DFFRX1 u_extract_o_valid_reg(.RN (rst_n), .CK (clk), .D (n_67), .Q
       (w_valid_1), .QN (UNCONNECTED84));
  NOR2X1 g12567__5115(.A (u_memory_trace[0]), .B (n_99), .Y (n_399));
  AOI22X1 g12593__7482(.A0 (u_memory_r2_t2[0]), .A1 (n_111), .B0
       (u_memory_r2_t7[0]), .B1 (n_102), .Y (n_98));
  AOI22X1 g12574__4733(.A0 (u_memory_r3_t4[0]), .A1 (n_116), .B0
       (u_memory_r3_t7[0]), .B1 (n_102), .Y (n_97));
  AOI22X1 g12575__6161(.A0 (u_memory_r1_t3[0]), .A1 (n_106), .B0
       (u_memory_r1_t6[0]), .B1 (n_105), .Y (n_96));
  AOI22X1 g12576__9315(.A0 (u_memory_r2_t3[0]), .A1 (n_106), .B0
       (u_memory_r2_t6[0]), .B1 (n_105), .Y (n_95));
  AOI22X1 g12577__9945(.A0 (u_memory_r2_t0[0]), .A1 (n_109), .B0
       (u_memory_r2_t1[0]), .B1 (n_108), .Y (n_94));
  AOI22X1 g12578__2883(.A0 (o_done), .A1 (n_619), .B0
       (u_traceback_tracing), .B1 (n_45), .Y (n_93));
  MX2X1 g12579__2346(.A (u_traceback_temp_data[2]), .B
       (u_traceback_temp_data[3]), .S0 (n_91), .Y (n_92));
  MX2X1 g12580__1666(.A (u_traceback_temp_data[5]), .B
       (u_traceback_temp_data[6]), .S0 (n_91), .Y (n_90));
  MX2X1 g12581__7410(.A (u_traceback_temp_data[1]), .B
       (u_traceback_temp_data[2]), .S0 (n_91), .Y (n_89));
  MX2X1 g12582__6417(.A (u_traceback_temp_data[0]), .B
       (u_traceback_temp_data[1]), .S0 (n_91), .Y (n_88));
  MX2X1 g12583__5477(.A (u_traceback_temp_data[3]), .B
       (u_traceback_temp_data[4]), .S0 (n_91), .Y (n_87));
  MX2X1 g12585__2398(.A (u_traceback_temp_data[6]), .B
       (u_traceback_temp_data[7]), .S0 (n_91), .Y (n_86));
  MX2X1 g12584__5107(.A (u_traceback_temp_data[4]), .B
       (u_traceback_temp_data[5]), .S0 (n_91), .Y (n_85));
  AOI22X1 g12573__6260(.A0 (u_traceback_current_node[0]), .A1 (n_141),
       .B0 (w_memory_done), .B1 (w_slt_node[0]), .Y (n_84));
  MX2X1 g12586__4319(.A (o_data[0]), .B (u_traceback_temp_data[0]), .S0
       (n_80), .Y (n_83));
  AOI22X1 g12557__8428(.A0 (n_461), .A1 (n_38), .B0
       (u_memory_count[2]), .B1 (n_37), .Y (n_82));
  MX2X1 g12591__5526(.A (o_data[3]), .B (u_traceback_temp_data[3]), .S0
       (n_80), .Y (n_81));
  MX2X1 g12571__6783(.A (o_data[7]), .B (u_traceback_temp_data[7]), .S0
       (n_80), .Y (n_79));
  DFFRX1 \u_extract_count_reg[2] (.RN (rst_n), .CK (clk), .D (n_54), .Q
       (u_extract_count[2]), .QN (n_31));
  MX2X1 g12587__3680(.A (o_data[4]), .B (u_traceback_temp_data[4]), .S0
       (n_80), .Y (n_78));
  MX2X1 g12589__1617(.A (o_data[1]), .B (u_traceback_temp_data[1]), .S0
       (n_80), .Y (n_77));
  OAI21X1 g12565__2802(.A0 (u_acs_pm_11[3]), .A1 (n_26), .B0 (n_40), .Y
       (n_186));
  MX2X1 g12592__1705(.A (o_data[5]), .B (u_traceback_temp_data[5]), .S0
       (n_80), .Y (n_76));
  INVX1 g12599(.A (n_63), .Y (n_75));
  OAI221X1 g12601__5122(.A0 (u_traceback_count[0]), .A1 (n_48), .B0
       (u_traceback_tracing), .B1 (n_6), .C0 (n_69), .Y (n_74));
  NAND2X1 g12594__8246(.A (n_272), .B (n_46), .Y (n_73));
  MX2X1 g12588__7098(.A (o_data[6]), .B (u_traceback_temp_data[6]), .S0
       (n_80), .Y (n_72));
  MX2X1 g12590__6131(.A (o_data[2]), .B (u_traceback_temp_data[2]), .S0
       (n_80), .Y (n_71));
  NAND2X1 g12597__5115(.A (u_traceback_count[0]), .B (n_141), .Y
       (n_151));
  DFFRX1 u_traceback_tracing_reg(.RN (rst_n), .CK (clk), .D (n_47), .Q
       (u_traceback_tracing), .QN (n_33));
  NAND3X1 g12602__7482(.A (n_69), .B (u_traceback_count[1]), .C (n_64),
       .Y (n_70));
  NAND2X1 g12544__4733(.A (n_124), .B (n_125), .Y (n_67));
  OAI211X1 g12559__6161(.A0 (n_14), .A1 (n_64), .B0 (n_69), .C0
       (u_traceback_count[2]), .Y (n_65));
  NOR2X1 g12547__9315(.A (i_start), .B (n_125), .Y (n_149));
  CLKAND2X2 g12548__9945(.A (n_124), .B (n_125), .Y (n_148));
  AOI22X1 g12603__2883(.A0 (u_memory_r0_t3[0]), .A1 (n_42), .B0
       (u_memory_r0_t6[0]), .B1 (n_49), .Y (n_63));
  AOI22X1 g12600__2346(.A0 (u_memory_r0_t0[0]), .A1 (n_61), .B0
       (u_memory_r0_t5[0]), .B1 (n_60), .Y (n_62));
  CLKINVX1 g12606(.A (n_286), .Y (n_59));
  NAND2X1 g12611__1666(.A (u_acs_pm_01[1]), .B (n_30), .Y (n_56));
  NAND2X1 g12596__7410(.A (n_55), .B (n_41), .Y (n_99));
  INVX2 g12608(.A (n_91), .Y (n_142));
  OAI21X1 g12542__6417(.A0 (n_35), .A1 (n_31), .B0 (n_124), .Y (n_54));
  NAND2X1 g12614__5477(.A (n_372), .B (u_acs_pm_00[0]), .Y (n_53));
  CLKINVX1 g12625(.A (n_51), .Y (n_52));
  NAND2X1 g12615__5107(.A (n_372), .B (n_271), .Y (n_57));
  NAND2X1 g12619__6260(.A (n_372), .B (u_acs_pm_10[3]), .Y (n_338));
  NAND2X1 g12618__4319(.A (n_372), .B (n_279), .Y (n_286));
  AND2X1 g12621__8428(.A (n_60), .B (u_memory_trace[1]), .Y (n_102));
  AND2X1 g12637__5526(.A (n_49), .B (u_memory_trace[1]), .Y (n_105));
  NAND2X1 g12624__6783(.A (n_69), .B (n_48), .Y (n_91));
  OAI21X1 g12595__3680(.A0 (n_33), .A1 (n_32), .B0 (n_69), .Y (n_47));
  NAND2X1 g12609__1617(.A (n_271), .B (n_29), .Y (n_46));
  CLKINVX1 g12626(.A (n_619), .Y (n_45));
  NAND2X1 g12612__2802(.A (u_memory_count[0]), .B (n_320), .Y (n_43));
  AND2X1 g12620__1705(.A (n_60), .B (n_195), .Y (n_114));
  NOR2X1 g12638__5122(.A (w_memory_done), .B (n_48), .Y (n_141));
  AND2X1 g12639__8246(.A (n_42), .B (u_memory_trace[1]), .Y (n_106));
  AND2X1 g12641__7098(.A (n_49), .B (n_195), .Y (n_116));
  AND2X1 g12642__6131(.A (n_42), .B (n_195), .Y (n_108));
  INVX2 g12607(.A (n_41), .Y (n_109));
  DFFRX1 u_memory_o_memory_done_reg(.RN (rst_n), .CK (clk), .D (n_21),
       .Q (w_memory_done), .QN (n_69));
  OAI21X1 g12630__1881(.A0 (u_acs_pm_01[2]), .A1 (n_263), .B0
       (u_acs_pm_01[3]), .Y (n_40));
  NAND2X1 g12613__5115(.A (u_acs_o_valid_d1), .B (w_slt_node[1]), .Y
       (n_39));
  NOR2X1 g12610__7482(.A (u_memory_count[2]), .B (n_37), .Y (n_38));
  AOI21X1 g12632__4733(.A0 (u_extract_count[0]), .A1
       (u_extract_count[1]), .B0 (n_35), .Y (n_36));
  AOI21X1 g12634__6161(.A0 (n_34), .A1 (u_acs_pm_11[4]), .B0 (w_sof_1),
       .Y (n_51));
  NOR2X1 g12617__9945(.A (w_sof_1), .B (u_acs_pm_01[2]), .Y (n_313));
  AND2X2 g12569__2883(.A (n_35), .B (n_31), .Y (n_125));
  CLKAND2X2 g12623__2346(.A (n_69), .B (n_32), .Y (n_80));
  CLKINVX1 g12643(.A (n_29), .Y (n_30));
  CLKINVX1 g12658(.A (n_27), .Y (n_28));
  NOR3X1 g12631__1666(.A (u_acs_pm_01[2]), .B (u_acs_pm_01[3]), .C
       (n_263), .Y (n_26));
  AOI22X1 g12627__7410(.A0 (u_acs_pm_01[3]), .A1 (n_34), .B0
       (u_acs_pm_01[2]), .B1 (n_263), .Y (n_25));
  NAND2X1 g12622__6417(.A (n_195), .B (n_61), .Y (n_41));
  NOR2X1 g12616__5477(.A (w_sof_1), .B (n_294), .Y (n_355));
  AND2X1 g12640__2398(.A (n_61), .B (u_memory_trace[1]), .Y (n_111));
  OR2X2 g12636__5107(.A (w_sof_1), .B (u_acs_pm_10[1]), .Y (n_304));
  INVX2 g12644(.A (n_320), .Y (n_461));
  NAND2X1 g12647__6260(.A (u_acs_pm_00[1]), .B (n_7), .Y (n_24));
  MX2X1 g12629__8428(.A (w_memory_done), .B (u_memory_read_hold), .S0
       (u_memory_read_mode), .Y (n_21));
  NAND2X1 g12649__5526(.A (n_33), .B (u_traceback_count[3]), .Y (n_20));
  OAI21X1 g12633__6783(.A0 (u_traceback_count[3]), .A1
       (u_traceback_count[0]), .B0 (u_traceback_tracing), .Y (n_64));
  NOR2X1 g12652__3680(.A (u_memory_trace[2]), .B (n_16), .Y (n_42));
  OR2X1 g12654__1617(.A (n_33), .B (u_traceback_count[3]), .Y (n_48));
  NOR2X1 g12653__2802(.A (u_memory_trace[0]), .B (n_15), .Y (n_49));
  NAND2X1 g12656__1705(.A (w_valid_3), .B (n_158), .Y (n_320));
  OR2X1 g12648__5122(.A (u_traceback_count[2]), .B (n_5), .Y (n_19));
  NAND2X1 g12661__8246(.A (u_acs_pm_00[3]), .B (n_3), .Y (n_18));
  NAND2X1 g12646__7098(.A (u_acs_pm_00[0]), .B (n_228), .Y (n_17));
  NOR2X1 g12650__6131(.A (u_memory_read_hold), .B (n_158), .Y (n_55));
  NAND2X1 g12651__1881(.A (u_acs_pm_01[0]), .B (n_223), .Y (n_29));
  NAND2X1 g12664__5115(.A (u_acs_pm_11[3]), .B (n_277), .Y (n_27));
  NAND2X1 g12662__7482(.A (u_acs_pm_10[3]), .B (n_384), .Y (n_219));
  NOR2X1 g12669__4733(.A (n_16), .B (n_15), .Y (n_60));
  NOR2X1 g12659__6161(.A (u_traceback_count[3]), .B
       (u_traceback_count[1]), .Y (n_14));
  NAND2X1 g12665__9315(.A (u_acs_pm_00[4]), .B (u_acs_pm_10[4]), .Y
       (n_13));
  NAND2X1 g12666__9945(.A (u_memory_count[0]), .B (u_memory_count[1]),
       .Y (n_37));
  NOR2X1 g12670__2883(.A (u_memory_trace[0]), .B (u_memory_trace[2]),
       .Y (n_61));
  NAND2X1 g12660__2346(.A (u_traceback_count[1]), .B
       (u_traceback_count[2]), .Y (n_12));
  NOR2X1 g12667__1666(.A (u_extract_count[0]), .B (u_extract_count[1]),
       .Y (n_35));
  DFFRX1 u_acs_o_valid_d1_reg(.RN (rst_n), .CK (clk), .D (w_valid_3),
       .Q (UNCONNECTED85), .QN (u_acs_o_valid_d1));
  CLKAND2X2 g12668__7410(.A (u_traceback_tracing), .B
       (u_traceback_count[3]), .Y (n_32));
  DFFRX4 u_extract_o_sof_reg(.RN (rst_n), .CK (clk), .D (i_start), .Q
       (w_sof_1), .QN (n_372));
  CLKINVX2 g12706(.A (i_start), .Y (n_124));
  CLKAND2X2 g2(.A (n_615), .B (n_372), .Y (n_616));
  CLKXOR2X1 g3(.A (u_acs_pm_11[1]), .B (n_222), .Y (n_615));
  OAI21X1 g12831(.A0 (n_36), .A1 (n_125), .B0 (n_124), .Y (n_617));
  OAI21X1 g12832(.A0 (u_extract_count[0]), .A1 (n_125), .B0 (n_124), .Y
       (n_618));
  NOR2X1 g12833(.A (n_33), .B (n_32), .Y (n_619));
  OR3X1 g12834(.A (n_494), .B (n_512), .C (n_505), .Y (n_620));
  CLKINVX1 g12835(.A (n_621), .Y (n_622));
  AOI21X1 g12836(.A0 (n_481), .A1 (n_490), .B0 (n_503), .Y (n_621));
  CLKINVX1 g12837(.A (n_623), .Y (n_624));
  OAI21X1 g12838(.A0 (n_57), .A1 (n_282), .B0 (n_312), .Y (n_623));
  MX2X1 g12839(.A (n_338), .B (u_acs_pm_10[3]), .S0 (n_291), .Y
       (n_625));
  CLKXOR2X1 g12840(.A (n_203), .B (n_253), .Y (n_626));
  XNOR2X1 g12841(.A (n_259), .B (n_225), .Y (n_627));
  CLKINVX1 g12842(.A (n_628), .Y (n_629));
  AOI22X1 g12843(.A0 (u_acs_pm_10[1]), .A1 (n_22), .B0 (n_17), .B1
       (n_24), .Y (n_628));
endmodule

